baseURL = "https://reusingthewheel.net/"
languageCode = "en-us"
title = "Reusing the wheel"
theme = "blank"
# disqusShortname = "piotr-rusin-github-io"
googleAnalytics = "UA-109495807-1"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4


[permalinks]
  posts = "/posts/:year-:month-:day-:filename/"

[menu]
  [[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 5
  [[menu.main]]
      url = "/categories/java"
      name = "Java"

[Params]
  description = "A blog about programming"
  readmore = true
  homeLinkText = "Reusing the wheel"
  github = "https://github.com/rtwnt"
  contact = "contact@reusingthewheel.net"

[Params.widgets]
    recent_articles = true
    recent_articles_num = 5
    categories = true
    tags = true
    social_github = "piotr-rusin"
    social_email = "contact@reusingthewheel.net"

[taxonomies]
    category = "categories"
    project = "projects"
